"""Data-driven per-model USD pricing.

Replaces the hardcoded `accounting.MODEL_PRICING` lookup table with a vendored
pricing dataset (`gatekeep/data/model_prices.json`) overlaid with optional
operator-supplied overrides. See issue #25 for the design.

Two kinds of baseline entry live in the vendored file:

- ``source == "litellm"``: regenerated by ``scripts/refresh_model_prices.py``
  from BerriAI/litellm's community pricing dataset. This is what removes the
  constant hand-maintenance of the old table for real, public models.
- ``source == "local"``: hand-maintained entries for models no public dataset
  knows about yet (preview/unreleased tiers, self-hosted or fine-tuned models).
  The refresh script preserves these across regenerations.

Operator overrides (a JSON file pointed at by ``Settings.pricing_overrides_path``)
win over both and are tagged ``source == "override"``.

`lookup` returns ``None`` on a miss rather than a zero price: a miss is an
explicit condition the caller must decide about (reject / ceiling / alert),
never a silent $0. This module only *reads* prices; it does not yet decide the
miss policy - that wiring lands in a later rollout step, and `accounting`
still uses the old table for now.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

# Of the four providers `resolve_route` can return, only these three are billed
# (ollama is self-hosted and genuinely free), so pricing only ever covers them -
# and the miss policy (issue #25) only ever governs them.
BILLED_PROVIDERS = frozenset({"anthropic", "openai", "google"})

# Maps a LiteLLM `litellm_provider` value onto one of our provider names. Only
# clean, unambiguous provider names are mapped; Vertex/Bedrock/Azure re-hosts
# of the same models are deliberately skipped to avoid two rows disagreeing on
# the price of one bare model id. "gemini" is Google AI Studio, which is the
# surface `Settings.google_api_key` / the google-genai provider targets.
_LITELLM_PROVIDER_MAP = {
    "openai": "openai",
    "anthropic": "anthropic",
    "gemini": "google",
}

_DEFAULT_BASELINE_PATH = Path(__file__).parent / "data" / "model_prices.json"


class PricingIntegrityError(RuntimeError):
    """Raised when the vendored pricing baseline fails its committed hash pin.

    The vendored ``model_prices.json`` is the spend-enforcement table, so a
    swap, partial write, or hand-edit that did not go back through
    ``scripts/refresh_model_prices.py`` (the only thing that re-pins it) must
    fail loudly rather than silently redefine what requests cost. See issue #25.
    """


def _pin_path_for(baseline_path: Path) -> Path:
    """Return the sibling ``.sha256`` lockfile path for a baseline JSON file."""
    return baseline_path.with_name(baseline_path.stem + ".sha256")


def compute_models_digest(models: Mapping[str, Any]) -> str:
    """Return the SHA-256 hex digest pinning a pricing file's `models` payload.

    Hashes only the ``models`` mapping - never ``_meta`` - so the pin tracks
    exactly the price content and is not churned by the ``generated_at`` stamp
    a no-op refresh rewrites. The canonical form sorts keys and drops
    whitespace, so file key ordering and pretty-print formatting do not affect
    the digest; only an actual change to a model or its price does.
    """
    canonical = json.dumps(models, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ModelPrice:
    """USD pricing for one model, expressed per one million tokens.

    Attributes:
        input_per_1m: USD charged per 1,000,000 input (prompt) tokens.
        output_per_1m: USD charged per 1,000,000 output (completion) tokens.
        source: Provenance of this entry - "litellm" (regenerated from the
            community dataset), "local" (hand-maintained), or "override"
            (operator-supplied). Carried for observability only; it does not
            affect the computed cost.
    """

    input_per_1m: float
    output_per_1m: float
    source: str

    def cost(self, prompt_tokens: int, completion_tokens: int) -> float:
        """Return the USD cost of `prompt_tokens`/`completion_tokens` at this price."""
        return (prompt_tokens / 1_000_000 * self.input_per_1m) + (
            completion_tokens / 1_000_000 * self.output_per_1m
        )


def _canonical_key(provider: str, model: str) -> str:
    """Build the vendored dataset key for a (provider, resolved-model) pair.

    Keys are ``"<provider>/<bare-model>"`` so the same bare model id served by
    two providers never collides, and so lookups key off the provider
    `resolve_route` already resolved rather than guessing from the model name.
    """
    return f"{provider}/{model}"


class PricingTable:
    """A resolved pricing table: vendored baseline overlaid with overrides."""

    def __init__(self, prices: Mapping[str, ModelPrice]) -> None:
        """Wrap an already-merged ``canonical-key -> ModelPrice`` mapping.

        Prefer `PricingTable.load` over calling this directly; it exists as the
        low-level constructor tests and the loader share.
        """
        self._prices: dict[str, ModelPrice] = dict(prices)

    @classmethod
    def load(
        cls,
        *,
        baseline_path: Path = _DEFAULT_BASELINE_PATH,
        overrides: Mapping[str, ModelPrice] | None = None,
    ) -> PricingTable:
        """Load the vendored baseline and overlay `overrides` on top.

        Args:
            baseline_path: Path to the vendored ``model_prices.json``.
            overrides: Operator-supplied ``canonical-key -> ModelPrice`` entries
                that win over baseline entries with the same key.

        Returns:
            A `PricingTable` combining both layers.

        Raises:
            FileNotFoundError: if `baseline_path` does not exist.
            ValueError: if the baseline file is malformed.
            PricingIntegrityError: if the baseline fails its committed hash pin.
        """
        raw = _read_pricing_json(baseline_path)
        models = raw.get("models", {})
        _verify_pin(baseline_path, models)
        prices = _entries_from_models(models, baseline_path)
        if overrides:
            prices.update(overrides)
        return cls(prices)

    def lookup(self, provider: str, model: str) -> ModelPrice | None:
        """Return the price for a (provider, resolved-model) pair, or None if unpriced.

        `provider`/`model` are exactly what `resolve_route` returns (the
        provider name and the prefix-stripped model id). A miss returns None;
        callers - not this table - decide what an unpriced model means.
        """
        return self._prices.get(_canonical_key(provider, model))

    def models_for_provider(self, provider: str) -> dict[str, ModelPrice]:
        """Return every priced model for `provider`, keyed by bare model id.

        Used by cost-based routing (`routing.select_model`) to enumerate
        candidate substitutes within the same provider as the requested
        model - crossing providers isn't safe there, since the caller already
        resolved a specific provider SDK client for the original request.
        """
        prefix = f"{provider}/"
        return {
            key[len(prefix) :]: price
            for key, price in self._prices.items()
            if key.startswith(prefix)
        }

    def __len__(self) -> int:
        """Return the number of priced models."""
        return len(self._prices)


def _read_pricing_json(path: Path) -> dict[str, Any]:
    """Read and parse a pricing JSON file into its raw ``{_meta, models}`` dict.

    Raises:
        FileNotFoundError: if `path` does not exist.
        ValueError: if the file is not valid JSON.
    """
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"malformed pricing file {path}: {exc}") from exc


def _entries_from_models(models: Mapping[str, Any], path: Path) -> dict[str, ModelPrice]:
    """Parse a raw ``models`` mapping into a ``canonical-key -> ModelPrice`` dict.

    Raises:
        ValueError: if an entry is missing a required numeric field.
    """
    entries: dict[str, ModelPrice] = {}
    for key, value in models.items():
        try:
            entries[key] = ModelPrice(
                input_per_1m=float(value["input_per_1m"]),
                output_per_1m=float(value["output_per_1m"]),
                source=str(value.get("source", "local")),
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(f"invalid pricing entry {key!r} in {path}: {exc}") from exc
    return entries


def _verify_pin(baseline_path: Path, models: Mapping[str, Any]) -> None:
    """Verify a baseline file's `models` against its committed ``.sha256`` pin.

    The default vendored baseline *must* carry a pin: a missing lockfile there
    is treated as a failure, so deleting the pin cannot silently disable the
    check on the enforcement path. Any other baseline path (test fixtures,
    an operator's alternate file) is only verified if a pin sits beside it, so
    ad-hoc files need not ship one.

    Raises:
        PricingIntegrityError: if the pin is required-but-absent, or present
            but does not match the file's `models` payload.
    """
    pin_path = _pin_path_for(baseline_path)
    if not pin_path.exists():
        if baseline_path == _DEFAULT_BASELINE_PATH:
            raise PricingIntegrityError(
                f"vendored pricing baseline {baseline_path} is missing its hash "
                f"pin {pin_path}; regenerate it with scripts/refresh_model_prices.py"
            )
        return
    expected = pin_path.read_text().strip()
    actual = compute_models_digest(models)
    if actual != expected:
        raise PricingIntegrityError(
            f"pricing baseline {baseline_path} does not match its hash pin "
            f"{pin_path} (expected {expected}, got {actual}); it was changed "
            f"without re-pinning - regenerate with scripts/refresh_model_prices.py"
        )


def _load_entries(path: Path) -> dict[str, ModelPrice]:
    """Parse a pricing JSON file into a ``canonical-key -> ModelPrice`` dict.

    Used for unpinned files (operator override layers); the pinned baseline
    goes through `PricingTable.load`, which additionally verifies the hash.

    Raises:
        FileNotFoundError: if `path` does not exist.
        ValueError: if the file is not valid JSON or an entry is missing a
            required numeric field.
    """
    raw = _read_pricing_json(path)
    return _entries_from_models(raw.get("models", {}), path)


def _load_overrides(path: Path) -> dict[str, ModelPrice]:
    """Load operator override entries from a JSON file, tagged ``source='override'``.

    The override file uses the same ``{"models": {key: {...}}}`` shape as the
    baseline; any ``source`` on its entries is ignored and forced to
    "override" so overlaid prices are always attributable as operator-set.
    """
    entries = _load_entries(path)
    return {
        key: ModelPrice(price.input_per_1m, price.output_per_1m, source="override")
        for key, price in entries.items()
    }


def is_billed_provider(provider: str) -> bool:
    """Return whether `provider` is one gatekeep pays an upstream for.

    Ollama is self-hosted and free, so it is never billed - and an unpriced
    Ollama model is expected, not a governance gap.
    """
    return provider in BILLED_PROVIDERS


def is_unpriced(provider: str, model: str) -> bool:
    """Return whether a (provider, model) is on a billed provider yet has no price.

    False for any Ollama model (never billed) and for any model the pricing
    table covers. True only for the case the miss policy exists to govern: a
    request that will cost real money upstream but that gatekeep cannot price.
    """
    return is_billed_provider(provider) and get_pricing_table().lookup(provider, model) is None


@lru_cache
def get_pricing_table() -> PricingTable:
    """Return the process-wide pricing table, built from settings.

    Loads the vendored baseline and, if ``Settings.pricing_overrides_path`` is
    set, overlays that override file. Cached for the process lifetime like
    `get_settings`; tests that need a fresh table call `get_pricing_table.cache_clear()`.
    """
    from gatekeep.config import get_settings

    settings = get_settings()
    overrides: dict[str, ModelPrice] | None = None
    if settings.pricing_overrides_path:
        overrides = _load_overrides(Path(settings.pricing_overrides_path))
    return PricingTable.load(overrides=overrides)


def transform_litellm(raw: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Transform a raw LiteLLM pricing dataset into our vendored entry schema.

    Pure (no network/IO) so it is unit-testable; the network fetch and file
    write live in ``scripts/refresh_model_prices.py``.

    Keeps only chat models on a billed provider we map (`_LITELLM_PROVIDER_MAP`)
    that carry both an input and output per-token price, converts per-token
    prices to per-1M, and re-keys them as ``"<provider>/<bare-model>"``.
    Non-chat modes, unmapped providers (Vertex/Bedrock/Azure re-hosts, audio,
    embeddings), and the dataset's ``sample_spec`` placeholder are skipped.

    Returns:
        A ``canonical-key -> {"input_per_1m", "output_per_1m", "source": "litellm"}``
        dict ready to merge into the vendored file.
    """
    entries: dict[str, dict[str, Any]] = {}
    for key, value in raw.items():
        if not isinstance(value, dict) or key == "sample_spec":
            continue
        if value.get("mode") != "chat":
            continue
        provider = _LITELLM_PROVIDER_MAP.get(value.get("litellm_provider"))
        if provider is None:
            continue
        input_cost = value.get("input_cost_per_token")
        output_cost = value.get("output_cost_per_token")
        if input_cost is None or output_cost is None:
            continue
        try:
            input_per_1m = round(float(input_cost) * 1_000_000, 6)
            output_per_1m = round(float(output_cost) * 1_000_000, 6)
        except (TypeError, ValueError):
            continue
        bare = key.split("/")[-1]
        entries[_canonical_key(provider, bare)] = {
            "input_per_1m": input_per_1m,
            "output_per_1m": output_per_1m,
            "source": "litellm",
        }
    return entries
