"""Data-driven per-model USD pricing.

Replaces the hardcoded `accounting.MODEL_PRICING` lookup table with a vendored
pricing dataset (`gatekeep/data/model_prices.json`) overlaid with optional
operator-supplied overrides. See issue #25 for the design.

Two kinds of baseline entry live in the vendored file:

- ``source == "litellm"``: regenerated by ``scripts/refresh_model_prices.py``
  from BerriAI/litellm's community pricing dataset. This is what removes the
  constant hand-maintenance of the old table for real, public models.
- ``source == "local"``: hand-maintained entries for models no public dataset
  knows about yet (preview/unreleased tiers, self-hosted or fine-tuned models).
  The refresh script preserves these across regenerations.

Operator overrides (a JSON file pointed at by ``Settings.pricing_overrides_path``)
win over both and are tagged ``source == "override"``.

`lookup` returns ``None`` on a miss rather than a zero price: a miss is an
explicit condition the caller must decide about (reject / ceiling / alert),
never a silent $0. This module only *reads* prices; it does not yet decide the
miss policy - that wiring lands in a later rollout step, and `accounting`
still uses the old table for now.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

# The four providers `resolve_route` can return. Only these three are billed
# (ollama is self-hosted and genuinely free), so pricing only ever covers them.
_BILLED_PROVIDERS = ("anthropic", "openai", "google")

# Maps a LiteLLM `litellm_provider` value onto one of our provider names. Only
# clean, unambiguous provider names are mapped; Vertex/Bedrock/Azure re-hosts
# of the same models are deliberately skipped to avoid two rows disagreeing on
# the price of one bare model id. "gemini" is Google AI Studio, which is the
# surface `Settings.google_api_key` / the google-genai provider targets.
_LITELLM_PROVIDER_MAP = {
    "openai": "openai",
    "anthropic": "anthropic",
    "gemini": "google",
}

_DEFAULT_BASELINE_PATH = Path(__file__).parent / "data" / "model_prices.json"


@dataclass(frozen=True)
class ModelPrice:
    """USD pricing for one model, expressed per one million tokens.

    Attributes:
        input_per_1m: USD charged per 1,000,000 input (prompt) tokens.
        output_per_1m: USD charged per 1,000,000 output (completion) tokens.
        source: Provenance of this entry - "litellm" (regenerated from the
            community dataset), "local" (hand-maintained), or "override"
            (operator-supplied). Carried for observability only; it does not
            affect the computed cost.
    """

    input_per_1m: float
    output_per_1m: float
    source: str

    def cost(self, prompt_tokens: int, completion_tokens: int) -> float:
        """Return the USD cost of `prompt_tokens`/`completion_tokens` at this price."""
        return (prompt_tokens / 1_000_000 * self.input_per_1m) + (
            completion_tokens / 1_000_000 * self.output_per_1m
        )


def _canonical_key(provider: str, model: str) -> str:
    """Build the vendored dataset key for a (provider, resolved-model) pair.

    Keys are ``"<provider>/<bare-model>"`` so the same bare model id served by
    two providers never collides, and so lookups key off the provider
    `resolve_route` already resolved rather than guessing from the model name.
    """
    return f"{provider}/{model}"


class PricingTable:
    """A resolved pricing table: vendored baseline overlaid with overrides."""

    def __init__(self, prices: Mapping[str, ModelPrice]) -> None:
        """Wrap an already-merged ``canonical-key -> ModelPrice`` mapping.

        Prefer `PricingTable.load` over calling this directly; it exists as the
        low-level constructor tests and the loader share.
        """
        self._prices: dict[str, ModelPrice] = dict(prices)

    @classmethod
    def load(
        cls,
        *,
        baseline_path: Path = _DEFAULT_BASELINE_PATH,
        overrides: Mapping[str, ModelPrice] | None = None,
    ) -> PricingTable:
        """Load the vendored baseline and overlay `overrides` on top.

        Args:
            baseline_path: Path to the vendored ``model_prices.json``.
            overrides: Operator-supplied ``canonical-key -> ModelPrice`` entries
                that win over baseline entries with the same key.

        Returns:
            A `PricingTable` combining both layers.

        Raises:
            FileNotFoundError: if `baseline_path` does not exist.
            ValueError: if the baseline file is malformed.
        """
        prices = _load_entries(baseline_path)
        if overrides:
            prices.update(overrides)
        return cls(prices)

    def lookup(self, provider: str, model: str) -> ModelPrice | None:
        """Return the price for a (provider, resolved-model) pair, or None if unpriced.

        `provider`/`model` are exactly what `resolve_route` returns (the
        provider name and the prefix-stripped model id). A miss returns None;
        callers - not this table - decide what an unpriced model means.
        """
        return self._prices.get(_canonical_key(provider, model))

    def models_for_provider(self, provider: str) -> dict[str, ModelPrice]:
        """Return every priced model for `provider`, keyed by bare model id.

        Used by cost-based routing (`routing.select_model`) to enumerate
        candidate substitutes within the same provider as the requested
        model - crossing providers isn't safe there, since the caller already
        resolved a specific provider SDK client for the original request.
        """
        prefix = f"{provider}/"
        return {
            key[len(prefix) :]: price
            for key, price in self._prices.items()
            if key.startswith(prefix)
        }

    def __len__(self) -> int:
        """Return the number of priced models."""
        return len(self._prices)


def _load_entries(path: Path) -> dict[str, ModelPrice]:
    """Parse a pricing JSON file into a ``canonical-key -> ModelPrice`` dict.

    Raises:
        FileNotFoundError: if `path` does not exist.
        ValueError: if the file is not valid JSON or an entry is missing a
            required numeric field.
    """
    try:
        raw = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ValueError(f"malformed pricing file {path}: {exc}") from exc
    models = raw.get("models", {})
    entries: dict[str, ModelPrice] = {}
    for key, value in models.items():
        try:
            entries[key] = ModelPrice(
                input_per_1m=float(value["input_per_1m"]),
                output_per_1m=float(value["output_per_1m"]),
                source=str(value.get("source", "local")),
            )
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(f"invalid pricing entry {key!r} in {path}: {exc}") from exc
    return entries


def _load_overrides(path: Path) -> dict[str, ModelPrice]:
    """Load operator override entries from a JSON file, tagged ``source='override'``.

    The override file uses the same ``{"models": {key: {...}}}`` shape as the
    baseline; any ``source`` on its entries is ignored and forced to
    "override" so overlaid prices are always attributable as operator-set.
    """
    entries = _load_entries(path)
    return {
        key: ModelPrice(price.input_per_1m, price.output_per_1m, source="override")
        for key, price in entries.items()
    }


@lru_cache
def get_pricing_table() -> PricingTable:
    """Return the process-wide pricing table, built from settings.

    Loads the vendored baseline and, if ``Settings.pricing_overrides_path`` is
    set, overlays that override file. Cached for the process lifetime like
    `get_settings`; tests that need a fresh table call `get_pricing_table.cache_clear()`.
    """
    from gatekeep.config import get_settings

    settings = get_settings()
    overrides: dict[str, ModelPrice] | None = None
    if settings.pricing_overrides_path:
        overrides = _load_overrides(Path(settings.pricing_overrides_path))
    return PricingTable.load(overrides=overrides)


def transform_litellm(raw: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """Transform a raw LiteLLM pricing dataset into our vendored entry schema.

    Pure (no network/IO) so it is unit-testable; the network fetch and file
    write live in ``scripts/refresh_model_prices.py``.

    Keeps only chat models on a billed provider we map (`_LITELLM_PROVIDER_MAP`)
    that carry both an input and output per-token price, converts per-token
    prices to per-1M, and re-keys them as ``"<provider>/<bare-model>"``.
    Non-chat modes, unmapped providers (Vertex/Bedrock/Azure re-hosts, audio,
    embeddings), and the dataset's ``sample_spec`` placeholder are skipped.

    Returns:
        A ``canonical-key -> {"input_per_1m", "output_per_1m", "source": "litellm"}``
        dict ready to merge into the vendored file.
    """
    entries: dict[str, dict[str, Any]] = {}
    for key, value in raw.items():
        if not isinstance(value, dict) or key == "sample_spec":
            continue
        if value.get("mode") != "chat":
            continue
        provider = _LITELLM_PROVIDER_MAP.get(value.get("litellm_provider"))
        if provider is None:
            continue
        input_cost = value.get("input_cost_per_token")
        output_cost = value.get("output_cost_per_token")
        if input_cost is None or output_cost is None:
            continue
        try:
            input_per_1m = round(float(input_cost) * 1_000_000, 6)
            output_per_1m = round(float(output_cost) * 1_000_000, 6)
        except (TypeError, ValueError):
            continue
        bare = key.split("/")[-1]
        entries[_canonical_key(provider, bare)] = {
            "input_per_1m": input_per_1m,
            "output_per_1m": output_per_1m,
            "source": "litellm",
        }
    return entries
